### ISSUE TITLE
Scrtipts missing?

### ISSUE THREAD

**Issue by f0rm4tm3** [andrewcell/Perry#90]
The git to the scripts is down, can you provide a download?

**Comment by f0rm4tm3** [comment]
Can you provide PerryScripts?

**Comment by andrewcell** [comment]
oh. I will check it and fix it if I can as soon as possible.

**Comment by andrewcell** [comment]
Oh. i will check it out and fix it as soon as possible

**Comment by f0rm4tm3** [comment]
Thanks

**Comment by andrewcell** [comment]
I found a other scripts repository uploaded by someone and It's kind of working with this server. Git submodule link is fixed. Mark as Closed.
